const MESSAGE_PREFIX = "COMPOSITEX_"
export const MESSAGE_TYPE_PREFIX = `${MESSAGE_PREFIX}SANDBOX_`
export const MESSAGE_TYPE = {
  Meta: `${MESSAGE_TYPE_PREFIX}META`,
  RunPipeline: `${MESSAGE_TYPE_PREFIX}RUN_PIPELINE`,
  RunPipelineProgress: `${MESSAGE_TYPE_PREFIX}RunPipelineProgress`,
}

export const MESSAGE_INSTALL_IN_WEBSITE = `${MESSAGE_PREFIX}_INSTALL_IN_WEBSITE`
export const MESSAGE_INSTALL_FROM_WEBSITE = `${MESSAGE_PREFIX}_INSTALL_FROM_WEBSITE`
export const MESSAGE_INSTALL_FROM_WEBSITE_REQUEST = `${MESSAGE_PREFIX}_INSTALL_FROM_WEBSITE_REQUEST`
